/*
* Constants used in the Milestone triggers and classes.
*/
public class MilestoneConstants {

    //Set up Milestone Names
    public static final String FIRST_RESPONSE = 'First Technical Response';
    public static final String ENG_ACK = 'Engineering Acknowledgement';
    public static final String ENG_FIX = 'Engineering Fix';
    public static final String ENG_STAGE = 'Staging and Test';
    public static final String REL_START  = 'Release Started';
    public static final String REL_FINISH = 'Release Finished';
    public static final String RESOLUTION = 'Resolution';
    
    //Set up Case Statuses and Engineering Statuses
    public static final String IN_QUEUE = 'In Queue';
    public static final String REJECTED = 'Rejected';
    public static final String ANSWERED = 'Answered';
    public static final String IMPLEMENTED = 'Implemented';
    public static final String STAGED = 'Staged';
    public static final String TESTED = 'Tested';
    public static final String DEPLOYED = 'Deployed';
    public static final String CLOSED = 'Closed';
    
    public MilestoneConstants() {}
}